const allJackets = [
  {
    name: "Warmy Adventure",
    price: 290,
    image: "../images/jacket-id1.jpg",
    id: 1,
    description: `<div class="jacket_intro"><p>One of our most popular jackets.</p> <p>A warm and durable jacket made to last.</p><p>3 layers of Dermizax 100% Polyester</p></div>`,
    featured: true,
    sales: true,
    male: true,
    female: true,
    rating: 5,
    sizes: ["S", "M", "L", "XL", "XXL"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
  {
    name: "Winter Spring",
    price: 199,
    image: "../images/jacket-id2.jpg",
    id: 2,
    description: "Swedish Coat: Gets you out of the comfort zone.",
    featured: true,
    sales: false,
    male: true,
    female: false,
    rating: 4,
    sizes: ["S", "M", "L", "XL"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
  {
    name: "NoCold Today",
    price: 275,
    image: "../images/jacket-id3.jpg",
    id: 3,
    description: "Swedish Coat: Gets you out of the comfort zone.",
    featured: true,
    sales: false,
    male: true,
    female: true,
    rating: 4,
    sizes: ["M", "L", "XL", "XXL"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
  {
    name: "Nordic Extreme",
    price: 290,
    image: "../images/jacket-id4.jpg",
    id: 4,
    description: "Swedish Coat: Gets you out of the comfort zone.",
    featured: true,
    sales: false,
    male: false,
    female: true,
    rating: 5,
    sizes: ["S", "M", "L"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
  {
    name: "Sunshine Ahead",
    price: 315,
    image: "../images/jacket-id5.jpg",
    id: 5,
    description: "Swedish Coat: Gets you out of the comfort zone.",
    featured: true,
    sales: false,
    male: false,
    female: true,
    rating: 3,
    sizes: ["S", "M", "L"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
  {
    name: "Sheep Alike",
    price: 300,
    image: "../images/jacket-id6.jpg",
    id: 6,
    description: "Swedish Coat: Gets you out of the comfort zone.",
    featured: true,
    sales: false,
    male: false,
    female: true,
    rating: 2,
    sizes: ["S", "M", "L", "XL"],
    reviewer: "John Doe, Oslo",
    reviewtext: "This is the best jacket I have ever owned. The perfect gift for everyone you know!",
  },
];
